# === USAGE ===
# See https://github.com/uiri/toml for more syntax related information.
#
# File and directory paths are denote with "_fp" (file path) and "_dp"
# (directory path).
#
# Boolean variables (such as "reconstruct_sfm_mvs" or "extract_pan") can be
# toggled with "1" and "0" or "true" and "false".

# Make sure that Meshlab has access to the "meshlab_temp_dp" directory below
# For example, the snap installation of Meshlab can NOT access /tmp
meshlab_server_fp = "/snap/bin/meshlab.meshlabserver"
meshlab_temp_dp = "/some/path/to/a/directory"

# Fill small holes, to compare results with VisSat
fill_small_holes = 1

# Possible values for sampling_method:
#   - vertex                # Reported in paper
#   - poisson_disk          # Reported in paper
#   - stratified_triangle
#   - montecarlo
sampling_method = "poisson_disk"

mesh_target_fn = "plain_mesh.ply"
algo_target_dn_list = [
    # "colmap_poisson",
    # "colmap_delaunay",
    # "openmvs",
    # "mve_fssr",
    "mve_gdmr",
    ]


# ===== Site 1 (Used in the VisSat Evaluation) =====
vissat_dataset_site_idp = "/path/to/VisSatDataset/site1-20201008T101440Z-001/site1"
vissat_fused_ifp = "/path/to/MVS3D_site_1_mvs/colmap/mvs/fused.ply"
meshes_idp = "/path/to/MVS3D_site_1_mesh/surface/meshing"
odp = "/path/to/MVS3D_site_1_evaluation"

# ===== Site 2 (Used in the VisSat Evaluation) =====
# vissat_dataset_site_idp = "/path/to/VisSatDataset/site2-20201008T101536Z-001/site2"
# vissat_fused_ifp = "/path/to/MVS3D_site_2_mvs/colmap/mvs/fused.ply"
# meshes_idp = "/path/to/MVS3D_site_2_mesh/surface/meshing"
# odp = "/path/to/MVS3D_site_2_evaluation"

# ===== Site 3 (Used in the VisSat Evaluation) =====
# vissat_dataset_site_idp = "/path/to/VisSatDataset/site3-20201008T101558Z-001/site3"
# vissat_fused_ifp = "/path/to/MVS3D_site_3_mvs/colmap/mvs/fused.ply"
# meshes_idp = "/path/to/MVS3D_site_3_mesh/surface/meshing"
# odp = "/path/to/MVS3D_site_3_evaluation"